services:
  - type: web
    name: chatbot-asma
    env: docker # <--- Change "python" par "docker" ici
    region: frankfurt
    plan: free
    branch: main
    # Supprime buildCommand et startCommand car le Dockerfile s'en occupe !
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: CHROMA_PERSIST_DIRECTORY
        value: /opt/render/project/src/chroma_db